### ISSUE TITLE
[BUG] Apple Silicon version is damaged and can't be opened

### ISSUE THREAD

**Issue by saa419** [tillvit/smeditor#156]
**Version/OS**
Version 1.0.0 (SMEditor-Mac-arm.zip)
OS: macOS Sequoia 15.1.1
Hardware: Tested on 2 machines:
- 2022 M2 MacBook Air
- 2024 M4 Mac mini

**Describe the bug**
Attempting to open the application opens a warning:
`"SMEditor" is damaged and can't be opened. You should move it to the Trash.`
The only options are Cancel (closes the warning and does not open the app) and Move to Trash (moves app file to trash)

**To Reproduce**
1. Download SMEditor-Mac-arm.zip on Apple Silicon from Github
2. Unzip
3. Move SMEditor to Applications folder
4. Open Application

**Screenshots/Media**
![Screenshot 2024-11-23 at 2 54 54 PM](https://github.com/user-attachments/assets/eb0774fc-9727-4476-aa6a-a7465befc2a1)

**Comment by tillvit** [comment]
I think this is caused by the app not being signed, but I think the error box is misleading (it used to say that the app was downloaded from an unknown source and would give you the option to open it).

If you want to work around it there are two ways:
1. Open Terminal and run `xattr -d com.apple.quarantine <path_to_SMEditor>` (this disables Apple's security check!)
2. Create a new folder, copy the contents of SMEditor inside (right-click & Show Package Contents on the original app), then rename the folder to SMEditor.app

Not sure if I'll get the app to be signed due to its cost
