### ISSUE TITLE
incorrect mp3 sync

### ISSUE THREAD

**Issue by mikatheidiot** [tillvit/smeditor#76]
for mp3 files, the audio playback and waveform are off sync, usually around 20 ms. can easily be seen when comparing to files synced in arrowvortex. issue does not exist for ogg audio

**Comment by tillvit** [comment]
Hmm, tried with some of my mp3s and they seem to be synced.
<img width="996" alt="Screenshot 2023-11-30 at 5 06 42 PM" src="https://github.com/tillvit/smeditor/assets/15373524/a3d9083c-e640-46b7-bd5b-285705c4f9f9">
<img width="1053" alt="Screenshot 2023-11-30 at 5 08 05 PM" src="https://github.com/tillvit/smeditor/assets/15373524/dabc6a78-afbb-408c-b375-8991bd50e138">

**Comment by tillvit** [comment]
Looked at the mp3 file through multiple different apps and it seems like it's not very consistent (probably depends on the decoding library used). Usually ogg is used more often in rhythm games because it's more consistent. I don't think I can fix this since I'm using the builtin decoding in the browser, while Stepmania 5.1 uses https://www.underbit.com/products/mad/.
