### ISSUE TITLE
Hold note placement stops when scrolling up

### ISSUE THREAD

**Issue by mangoafterdawn** [tillvit/smeditor#80]
Placing down a hold note will have the hold's note be placed down if you scroll above the first placement of the note, instead of extending the hold note upwards
![SMEditor_qlXvmiDNNT](https://github.com/tillvit/smeditor/assets/55304988/c1b0bb3e-87f5-4687-9a5d-be25c25a8c26)

**Comment by tillvit** [comment]
This was actually the original behavior but someone suggested it should have this behavior
There is a tradeoff between the two behaviors; with the new behavior you give up the ability to extend holds upwards but you can undo your hold length if you stretch too far. I prefer the new behavior because you can just drag the note up if you wanted to "extend" the hold upwards but I think this is valid for a discussion

**Comment by tillvit** [comment]
New behavior:
https://github.com/user-attachments/assets/da8858ce-ff7b-43fc-9a7b-bbc8300b4739

Whichever direction you initially extend the hold will be the only direction you can extend it. You can disable this behavior in settings
